import type { ServiceConfig, ServiceCategory } from "@exvion/types";

export const services: ServiceConfig[] = [
  {
    id: "ai-workflow",
    slug: "ai-workflow-integration",
    order: 1,
    title: "AI Workflow Integration for SMBs",
    shortTitle: "AI Workflow Integration",
    tagline: "Stop doing manually what AI can do for you.",
    description: "We map your business processes and integrate AI automation that eliminates repetitive tasks, speeds up decisions, and cuts operational overhead — without disrupting your existing team or tools.",
    category: "ai",
    heroHeadline: "Your Business Runs Faster When AI Does the Heavy Lifting",
    heroSub: "We find where your team wastes the most time and replace those bottlenecks with intelligent AI workflows that operate 24/7 without supervision.",
    problemHeadline: "Manual Work Is Silently Eating Your Margins Every Day",
    problems: [
      "Your team spends hours on tasks AI could handle in seconds",
      "Data scattered across tools with no intelligent connection",
      "Slow response times because humans are stuck in every loop",
      "No visibility into which processes are costing you most",
    ],
    solutionHeadline: "AI Workflows Built Around How You Actually Operate",
    solutionDesc: "We audit your operations, identify the highest-ROI automation points, and deploy AI that integrates with your existing stack. The result is a leaner, faster operation with fewer errors and lower cost per task.",
    outcomes: [
      "40–70% reduction in manual operational tasks",
      "Faster customer response and processing times",
      "Lower cost per operational unit",
      "Full visibility into automated workflows",
    ],
    whoItFor: [
      "SMB owners drowning in repetitive operational tasks",
      "Teams managing high-volume data or communication",
      "Service businesses losing leads from slow follow-up",
      "Companies wanting AI but unsure where to start",
    ],
    useCases: [
      { label: "Automated lead follow-up and nurturing" },
      { label: "Invoice and document processing" },
      { label: "Customer support triage and routing" },
      { label: "Inventory and order automation" },
      { label: "Report generation and data aggregation" },
    ],
    process: [
      { step: "01", title: "Workflow Audit", desc: "Map every manual process across your operation" },
      { step: "02", title: "ROI Prioritization", desc: "Identify highest-value automation targets" },
      { step: "03", title: "AI Integration", desc: "Build and connect AI systems to your tools" },
      { step: "04", title: "Monitor & Optimize", desc: "Track results and continuously improve" },
    ],
    startingPrice: "₹40,000",
    deliveryTime: "2–4 weeks",
    formConfig: "ai-workflow",
    featured: true,
    iconId: "ai-workflow",
    accentColor: "#8B5CF6",
    gradientFrom: "rgba(139,92,246,0.12)",
  },
  {
    id: "white-label-saas",
    slug: "white-label-saas-setup",
    order: 2,
    title: "White-Label SaaS Setup for Agencies",
    shortTitle: "White-Label SaaS",
    tagline: "Your brand. Our build. Their subscription.",
    description: "Launch a fully branded SaaS product under your agency's name without building from scratch. We configure, brand, and deploy proven SaaS systems so you can sell recurring software to clients from day one.",
    category: "saas",
    heroHeadline: "Launch a SaaS Product Under Your Brand — Without Building One",
    heroSub: "Your clients see your brand. You keep the revenue. We stay invisible and handle every technical detail of the setup.",
    problemHeadline: "Agencies Are Leaving Recurring Revenue on the Table",
    problems: [
      "Clients asking for software solutions you can't deliver",
      "Building SaaS from scratch takes months and large budgets",
      "Competitor agencies already offering platform products",
      "No recurring revenue stream from your existing client base",
    ],
    solutionHeadline: "A Fully Branded SaaS Product Your Clients Pay for Monthly",
    solutionDesc: "We select the right SaaS base, white-label it with your branding, configure pricing tiers and client onboarding, and hand you a product you can sell immediately under your own name.",
    outcomes: [
      "Launch white-label SaaS in 7–14 days",
      "New recurring revenue from existing clients",
      "Zero development overhead or team required",
      "Full control over pricing and client management",
    ],
    whoItFor: [
      "Digital agencies wanting to offer SaaS products",
      "Consultants building productized services",
      "Resellers building scalable revenue streams",
      "Entrepreneurs entering SaaS without a technical team",
    ],
    useCases: [
      { label: "White-label CRM for agency clients" },
      { label: "Branded project management tools" },
      { label: "Client-facing reporting dashboards" },
      { label: "Resellable booking and scheduling platforms" },
      { label: "White-label email marketing tools" },
    ],
    process: [
      { step: "01", title: "Platform Selection", desc: "Choose the right SaaS base for your market" },
      { step: "02", title: "Branding Setup", desc: "Apply your logo, colors, domain, and copy" },
      { step: "03", title: "Configuration", desc: "Set up pricing, onboarding, and client access" },
      { step: "04", title: "Launch Support", desc: "Go live with docs and reseller support" },
    ],
    startingPrice: "₹35,000",
    deliveryTime: "7–14 days",
    formConfig: "white-label-saas",
    featured: true,
    iconId: "white-label",
    accentColor: "#0EA5E9",
    gradientFrom: "rgba(14,165,233,0.12)",
  },
  {
    id: "wp-plugin",
    slug: "custom-wordpress-plugin-development",
    order: 3,
    title: "Custom WordPress Plugin Development",
    shortTitle: "WP Plugin Development",
    tagline: "If WordPress can't do it out of the box, we build it.",
    description: "Custom WordPress plugins built precisely for your business logic — not patched together from generic solutions. Clean, performant, and built to work exactly the way you need.",
    category: "wordpress",
    heroHeadline: "WordPress Plugins Built for Your Business, Not Someone Else's",
    heroSub: "Stop forcing your workflows into plugins built for generic use cases. We build exactly what your site needs — nothing more, nothing less.",
    problemHeadline: "Generic Plugins Create More Problems Than They Solve",
    problems: [
      "Off-the-shelf plugins don't match your business workflow",
      "Plugin bloat and conflicts slowing your site down",
      "Paying for features you never use",
      "Updates breaking your site with no warning",
    ],
    solutionHeadline: "Exactly the Functionality You Need. Zero Bloat.",
    solutionDesc: "We scope your exact requirements, build a clean performant plugin with no unnecessary code, and deliver full source ownership with documentation your team can maintain.",
    outcomes: [
      "Exact functionality with zero unnecessary features",
      "Better site performance than generic alternatives",
      "Full source code ownership",
      "Documentation for your team to manage long-term",
    ],
    whoItFor: [
      "WordPress site owners with unique functionality gaps",
      "WooCommerce stores needing custom checkout logic",
      "Businesses running WordPress as a core platform",
      "Agencies needing reusable plugin solutions for clients",
    ],
    useCases: [
      { label: "Custom WooCommerce pricing engines" },
      { label: "Membership and access control systems" },
      { label: "Custom lead capture and form systems" },
      { label: "Payment gateway integrations" },
      { label: "Custom admin dashboard plugins" },
    ],
    process: [
      { step: "01", title: "Requirements", desc: "Define exact functionality and business logic" },
      { step: "02", title: "Architecture", desc: "Plan plugin structure and integration points" },
      { step: "03", title: "Development", desc: "Build with clean, documented PHP and JavaScript" },
      { step: "04", title: "Test & Deploy", desc: "Thorough testing and live deployment" },
    ],
    startingPrice: "₹15,000",
    deliveryTime: "1–3 weeks",
    formConfig: "wp-plugin",
    featured: false,
    iconId: "wordpress",
    accentColor: "#21759B",
    gradientFrom: "rgba(33,117,155,0.12)",
  },
  {
    id: "maintenance",
    slug: "saas-maintenance-plans",
    order: 4,
    title: "Monthly SaaS / Script Maintenance Plans",
    shortTitle: "Maintenance Plans",
    tagline: "Your platform never sleeps. Neither do we.",
    description: "Ongoing technical maintenance for SaaS platforms and custom scripts — updates, bug fixes, performance monitoring, security patches, and proactive issue resolution on a predictable monthly retainer.",
    category: "maintenance",
    heroHeadline: "Your Platform Deserves Consistent Technical Care",
    heroSub: "A dedicated monthly maintenance plan that keeps your platform fast, secure, and free of bugs — so you can focus on growing it.",
    problemHeadline: "Unmonitored Platforms Fail at the Worst Possible Times",
    problems: [
      "Critical bugs discovered by users instead of caught proactively",
      "Security vulnerabilities unpatched for months",
      "Performance degrading silently as traffic grows",
      "No one watching your platform every day",
    ],
    solutionHeadline: "A Technical Team Watching Your Platform Every Month",
    solutionDesc: "We become your on-call engineering team. Monthly plans include proactive monitoring, updates, bug resolution, performance optimization, and a defined response time SLA.",
    outcomes: [
      "Zero surprise downtime or critical bug events",
      "Always current with security patches",
      "Maintained performance as you scale",
      "Predictable cost vs reactive emergency fixes",
    ],
    whoItFor: [
      "SaaS founders without a dedicated tech team",
      "Businesses running custom-built platforms",
      "Agencies managing client platforms",
      "Entrepreneurs who built once and need ongoing care",
    ],
    useCases: [
      { label: "Monthly WordPress and plugin updates" },
      { label: "SaaS platform performance monitoring" },
      { label: "Security audits and patching" },
      { label: "Bug fixes and minor improvements" },
      { label: "Database optimization and cleanup" },
    ],
    process: [
      { step: "01", title: "Platform Audit", desc: "Assess the current state of your system" },
      { step: "02", title: "Plan Selection", desc: "Choose the right coverage tier for your needs" },
      { step: "03", title: "Onboarding", desc: "Access handoff and baseline documentation" },
      { step: "04", title: "Monthly Cycle", desc: "Regular updates, reports, and fixes" },
    ],
    startingPrice: "₹8,000/mo",
    deliveryTime: "Monthly retainer",
    formConfig: "maintenance",
    featured: false,
    iconId: "maintenance",
    accentColor: "#10B981",
    gradientFrom: "rgba(16,185,129,0.12)",
  },
  {
    id: "feature-dev",
    slug: "custom-feature-development",
    order: 5,
    title: "Custom Feature Development (Retainer)",
    shortTitle: "Feature Development",
    tagline: "Your product roadmap executed on schedule, every month.",
    description: "A dedicated development retainer for SaaS and product teams who need consistent feature delivery — new functionality, integrations, and technical improvements shipped on a predictable monthly cycle.",
    category: "development",
    heroHeadline: "Ship New Features Every Month Without Hiring Full-Time",
    heroSub: "A retainer-based engineering team that plugs directly into your product roadmap and delivers features on a consistent, reliable schedule.",
    problemHeadline: "Stalled Roadmaps Kill Momentum and Lose Users",
    problems: [
      "Features taking months to ship instead of weeks",
      "Freelancers delivering inconsistent quality and availability",
      "Falling behind competitors due to slow iteration",
      "Overhead of hiring and managing full-time developers",
    ],
    solutionHeadline: "Consistent Feature Delivery on a Predictable Monthly Retainer",
    solutionDesc: "We dedicate development capacity to your product every month. Features are planned, built, tested, and shipped on a consistent cycle — with the output of a dev team and none of the hiring overhead.",
    outcomes: [
      "Predictable monthly feature delivery",
      "No hiring or management overhead",
      "Consistent code quality and documentation",
      "Faster time-to-market on every feature",
    ],
    whoItFor: [
      "SaaS founders with active products and growing roadmaps",
      "Startups needing lean development between funding rounds",
      "Product managers needing reliable engineering output",
      "Businesses scaling features without scaling headcount",
    ],
    useCases: [
      { label: "Monthly development sprints" },
      { label: "Third-party API integrations" },
      { label: "UI and UX improvements" },
      { label: "Performance and scalability work" },
      { label: "Technical debt resolution" },
    ],
    process: [
      { step: "01", title: "Roadmap Review", desc: "Understand your product goals and priorities" },
      { step: "02", title: "Sprint Planning", desc: "Define monthly deliverables and scope" },
      { step: "03", title: "Development", desc: "Build, test, and document each feature" },
      { step: "04", title: "Delivery", desc: "Ship and review with your team monthly" },
    ],
    startingPrice: "₹25,000/mo",
    deliveryTime: "Monthly retainer",
    formConfig: "feature-dev",
    featured: true,
    iconId: "feature-dev",
    accentColor: "#F59E0B",
    gradientFrom: "rgba(245,158,11,0.12)",
  },
  {
    id: "product-strategy",
    slug: "product-strategy-consulting",
    order: 6,
    title: "Product Strategy Consulting for SaaS Founders",
    shortTitle: "Product Strategy",
    tagline: "Build the right thing before you build it right.",
    description: "Strategic advisory for SaaS founders on product-market fit, feature prioritization, monetization models, and scaling decisions — grounded in real execution experience, not just theory.",
    category: "consulting",
    heroHeadline: "The Right Strategy Saves You Six Months and Six Figures",
    heroSub: "We work with SaaS founders to define what to build, who to build it for, and how to turn a product into a scalable, profitable business.",
    problemHeadline: "Most SaaS Products Fail Because of Strategy, Not Technology",
    problems: [
      "Building features users asked for but don't actually pay for",
      "No clear market differentiation from competitors",
      "Monetization that doesn't match how users get value",
      "Growing the product in the wrong direction for months",
    ],
    solutionHeadline: "Clarity Before Code. Strategy Before Every Sprint.",
    solutionDesc: "Structured consulting that aligns your product with your market, your pricing with your value, and your roadmap with business outcomes — so every build decision has strategic backing.",
    outcomes: [
      "Clear product-market fit direction",
      "Validated monetization model",
      "Prioritized roadmap backed by real data",
      "Defined competitive positioning",
    ],
    whoItFor: [
      "Early-stage SaaS founders pre or post-launch",
      "Founders pivoting or repositioning their product",
      "Technical founders needing business strategy input",
      "SaaS teams stuck in low-growth plateau",
    ],
    useCases: [
      { label: "Product-market fit validation" },
      { label: "Pricing and monetization strategy" },
      { label: "Roadmap prioritization frameworks" },
      { label: "Competitive analysis and positioning" },
      { label: "Growth planning sessions" },
    ],
    process: [
      { step: "01", title: "Discovery", desc: "Deep dive into your product, users, and goals" },
      { step: "02", title: "Audit", desc: "Analyze current product, metrics, and market" },
      { step: "03", title: "Strategy Session", desc: "Frameworks and actionable recommendations" },
      { step: "04", title: "Roadmap Delivery", desc: "Execution plan with milestones" },
    ],
    startingPrice: "₹20,000",
    deliveryTime: "1–2 weeks",
    formConfig: "product-strategy",
    featured: false,
    iconId: "strategy",
    accentColor: "#6366F1",
    gradientFrom: "rgba(99,102,241,0.12)",
  },
  {
    id: "ai-chatbot",
    slug: "ai-chatbot-development",
    order: 7,
    title: "AI Chatbot Development",
    shortTitle: "AI Chatbot",
    tagline: "Your best salesperson. Works 24/7. Never burns out.",
    description: "Intelligent AI chatbots trained on your business data — for customer support, lead qualification, or sales assistance. Not generic chat widgets. Real AI that understands your products, handles objections, and knows when to escalate.",
    category: "ai",
    heroHeadline: "An AI That Knows Your Business Inside Out",
    heroSub: "Custom-trained chatbots that handle inquiries, qualify leads, and support customers — deployed on your website, WhatsApp, or internal tools.",
    problemHeadline: "Slow Responses Are Costing You Leads and Customers",
    problems: [
      "Leads dropping off because no one responds within minutes",
      "Support team overwhelmed by repetitive questions",
      "Inconsistent brand responses frustrating customers",
      "High cost of human support at scale",
    ],
    solutionHeadline: "An AI That Speaks for Your Brand Around the Clock",
    solutionDesc: "We build, train, and deploy AI chatbots that understand your products, handle objections, qualify leads, and hand off complex cases to your team — fully integrated with your existing tools.",
    outcomes: [
      "Instant response to every lead and inquiry",
      "50–70% reduction in support workload",
      "Consistent brand voice in every interaction",
      "Higher lead qualification and conversion",
    ],
    whoItFor: [
      "Businesses with high inquiry or support volume",
      "SaaS companies needing intelligent onboarding flows",
      "E-commerce stores wanting 24/7 support",
      "Service businesses automating lead qualification",
    ],
    useCases: [
      { label: "Lead qualification chatbots" },
      { label: "Customer support and FAQ automation" },
      { label: "Sales assistant and product guidance" },
      { label: "Internal HR and knowledge base bots" },
      { label: "WhatsApp business automation" },
    ],
    process: [
      { step: "01", title: "Training Data", desc: "Gather product knowledge and common queries" },
      { step: "02", title: "Flow Design", desc: "Define conversation paths and escalation logic" },
      { step: "03", title: "Build & Train", desc: "Develop and train the AI on your data" },
      { step: "04", title: "Deploy & Tune", desc: "Launch and optimize based on real usage" },
    ],
    startingPrice: "₹30,000",
    deliveryTime: "2–3 weeks",
    formConfig: "ai-chatbot",
    featured: true,
    iconId: "chatbot",
    accentColor: "#EC4899",
    gradientFrom: "rgba(236,72,153,0.12)",
  },
  {
    id: "mvp-build",
    slug: "build-your-mvp",
    order: 8,
    title: "Build Your MVP",
    shortTitle: "MVP Development",
    tagline: "From idea to live product in weeks, not months.",
    description: "We take your validated idea and ship a production-ready MVP fast. Clean architecture, real users can actually use it, and built on a foundation that scales when you grow.",
    category: "development",
    heroHeadline: "Your Idea Deserves a Real Product, Not a Prototype",
    heroSub: "We build MVPs that are production-ready from day one — designed to validate your concept, attract early users, and scale into a full product.",
    problemHeadline: "Most MVPs Either Take Too Long or Break Too Fast",
    problems: [
      "Spending months building before getting any user feedback",
      "MVPs built so poorly they have to be entirely rebuilt",
      "Agencies bloating scope instead of keeping it lean",
      "No clear feature scope — endless creep before launch",
    ],
    solutionHeadline: "A Lean, Scalable MVP That Gets You to Market Fast",
    solutionDesc: "We define strict MVP scope with you, build only what matters for validation, and deliver a product real users can interact with — on a foundation that scales when you raise or grow.",
    outcomes: [
      "Live product in 4–8 weeks",
      "Scalable architecture from day one",
      "Real user feedback within weeks of starting",
      "Defined scope with zero feature creep",
    ],
    whoItFor: [
      "Founders with validated ideas ready to build",
      "Entrepreneurs transitioning from concept to product",
      "Businesses testing new digital product lines",
      "Startups preparing for early user acquisition",
    ],
    useCases: [
      { label: "Web application MVPs" },
      { label: "Mobile-first web products" },
      { label: "B2B tool prototypes" },
      { label: "Internal tool MVPs" },
      { label: "SaaS first versions" },
    ],
    process: [
      { step: "01", title: "Scope Lock", desc: "Define the exact MVP feature set — no more, no less" },
      { step: "02", title: "Design Sprint", desc: "UI/UX built for user validation" },
      { step: "03", title: "Development", desc: "Build with scalable architecture and clean code" },
      { step: "04", title: "Launch", desc: "Deploy, onboard first users, and collect feedback" },
    ],
    startingPrice: "₹60,000",
    deliveryTime: "4–8 weeks",
    formConfig: "mvp-build",
    featured: true,
    iconId: "mvp",
    accentColor: "#FB4E00",
    gradientFrom: "rgba(251,78,0,0.12)",
  },
  {
    id: "saas-mvp",
    slug: "saas-mvp-development",
    order: 9,
    title: "SaaS MVP Development",
    shortTitle: "SaaS MVP",
    tagline: "Launch your SaaS before your competitors catch up.",
    description: "Purpose-built SaaS MVP with subscription billing, user authentication, role-based access, admin dashboard, and the core feature users will actually pay for. Built to launch, not just demonstrate.",
    category: "saas",
    heroHeadline: "Your SaaS Needs Real Infrastructure, Not Just a Pretty UI",
    heroSub: "We build SaaS MVPs with proper auth, billing, permissions, and admin systems — the complete technical foundation from day one.",
    problemHeadline: "SaaS MVPs Fail When Core Infrastructure Is an Afterthought",
    problems: [
      "Launching without subscription billing working correctly",
      "No role-based access system from the start",
      "Missing admin panel — can't manage users or data",
      "Authentication built incorrectly causing security failures",
    ],
    solutionHeadline: "The Complete SaaS Foundation Built Right the First Time",
    solutionDesc: "We build your SaaS MVP with all critical infrastructure — Stripe billing, JWT auth, role permissions, transactional email, admin panel, and your core differentiating feature. Ready to charge from day one.",
    outcomes: [
      "Complete SaaS infrastructure in 6–10 weeks",
      "Subscription billing working from launch",
      "Secure auth and role-based access",
      "Admin panel ready for user and data management",
    ],
    whoItFor: [
      "Founders building subscription software products",
      "Agencies building SaaS platforms for clients",
      "Technical founders wanting a complete foundation",
      "Businesses productizing their service into software",
    ],
    useCases: [
      { label: "B2B subscription software" },
      { label: "Vertical SaaS for specific industries" },
      { label: "Internal tools with subscription access" },
      { label: "Multi-tenant SaaS platforms" },
      { label: "API-based SaaS products" },
    ],
    process: [
      { step: "01", title: "Architecture Plan", desc: "Design tech stack, schema, and system structure" },
      { step: "02", title: "Core Build", desc: "Auth, billing, permissions, and admin system" },
      { step: "03", title: "Feature Build", desc: "Your core differentiating product feature" },
      { step: "04", title: "Launch Ready", desc: "Deploy with full documentation and handoff" },
    ],
    startingPrice: "₹80,000",
    deliveryTime: "6–10 weeks",
    formConfig: "saas-mvp",
    featured: true,
    iconId: "saas-mvp",
    accentColor: "#06B6D4",
    gradientFrom: "rgba(6,182,212,0.12)",
  },
  {
    id: "marketplace",
    slug: "marketplace-development",
    order: 10,
    title: "Marketplace Platform Development",
    shortTitle: "Marketplace Development",
    tagline: "Build the platform. Let others do the selling.",
    description: "Full-stack marketplace development with multi-vendor management, automated payouts, buyer and seller panels, commission systems, and the performance architecture to handle real transaction volume.",
    category: "development",
    heroHeadline: "Build a Marketplace Business That Scales on Its Own",
    heroSub: "Multi-vendor systems with automated payouts, smart admin tools, and the architecture to handle thousands of transactions without breaking.",
    problemHeadline: "Marketplaces Break When Architecture Is Ignored Early",
    problems: [
      "No multi-vendor management or payout system",
      "Manual order and payment processing that doesn't scale",
      "No vendor onboarding or commission automation",
      "Performance collapsing under growing inventory",
    ],
    solutionHeadline: "End-to-End Marketplace Infrastructure Built to Scale",
    solutionDesc: "We build complete marketplace platforms with vendor panels, smart admin automation, payout systems, and optimized architecture that handles growth without requiring a rebuild.",
    outcomes: [
      "Full multi-vendor marketplace in 8–14 weeks",
      "Automated vendor payouts and commissions",
      "Scalable performance architecture",
      "Admin control over every vendor and transaction",
    ],
    whoItFor: [
      "Entrepreneurs building marketplace businesses",
      "Businesses moving to multi-vendor online models",
      "Agencies building marketplace solutions for clients",
      "Founders in e-commerce, services, or digital products",
    ],
    useCases: [
      { label: "E-commerce multi-vendor marketplaces" },
      { label: "Service marketplace platforms" },
      { label: "Digital product distribution platforms" },
      { label: "On-demand service platforms" },
      { label: "Rental and booking marketplaces" },
    ],
    process: [
      { step: "01", title: "Business Model", desc: "Define vendor structure, commissions, and payouts" },
      { step: "02", title: "Platform Design", desc: "UX for buyers, vendors, and admins" },
      { step: "03", title: "Development", desc: "Build all panels and automated transaction flows" },
      { step: "04", title: "Go Live", desc: "Launch with vendor onboarding support" },
    ],
    startingPrice: "₹1,20,000",
    deliveryTime: "8–14 weeks",
    formConfig: "marketplace",
    featured: true,
    iconId: "marketplace",
    accentColor: "#3B82F6",
    gradientFrom: "rgba(59,130,246,0.12)",
  },
  {
    id: "business-automation",
    slug: "business-workflow-automation",
    order: 11,
    title: "Business Workflow Automation System",
    shortTitle: "Business Automation",
    tagline: "Automate the work. Keep the people for what matters.",
    description: "End-to-end business process automation that connects your tools, eliminates manual handoffs, and runs your operations on autopilot — from lead capture through fulfillment and follow-up.",
    category: "automation",
    heroHeadline: "Your Business Should Run While You Focus on Growing It",
    heroSub: "We design and deploy automation systems that connect every tool in your stack and eliminate the manual handoffs costing your team hours every day.",
    problemHeadline: "Manual Handoffs Between Tools Create Errors and Delays",
    problems: [
      "Information stuck in one tool that another needs immediately",
      "Team spending hours on manual data entry and transfers",
      "Errors from human touchpoints in critical workflows",
      "No consistent process — everything depends on one person",
    ],
    solutionHeadline: "Connected Systems That Run Your Operations Automatically",
    solutionDesc: "We map your full operation, design the automation architecture, and deploy connected workflows that move data, trigger actions, and complete processes without anyone lifting a finger.",
    outcomes: [
      "Critical workflows running fully automated",
      "Elimination of manual data entry errors",
      "Consistent process execution every time",
      "Team freed from operational overhead",
    ],
    whoItFor: [
      "Businesses with complex multi-tool operations",
      "Teams spending hours on manual data work",
      "Growing companies with inconsistent processes",
      "Operations managers seeking control and visibility",
    ],
    useCases: [
      { label: "CRM to project management automation" },
      { label: "Sales pipeline and follow-up automation" },
      { label: "Invoice and payment workflow automation" },
      { label: "HR onboarding and offboarding systems" },
      { label: "Reporting and analytics automation" },
    ],
    process: [
      { step: "01", title: "Process Mapping", desc: "Document every workflow and tool touchpoint" },
      { step: "02", title: "Architecture", desc: "Design the complete automation system" },
      { step: "03", title: "Build & Connect", desc: "Deploy integrations and automation logic" },
      { step: "04", title: "Handoff & Train", desc: "Train your team and monitor live performance" },
    ],
    startingPrice: "₹45,000",
    deliveryTime: "3–5 weeks",
    formConfig: "business-automation",
    featured: false,
    iconId: "automation",
    accentColor: "#F97316",
    gradientFrom: "rgba(249,115,22,0.12)",
  },
  {
    id: "startup-landing",
    slug: "startup-landing-page",
    order: 12,
    title: "Startup Landing Page (Conversion-Focused)",
    shortTitle: "Startup Landing Page",
    tagline: "A landing page that works as hard as you do.",
    description: "High-converting startup landing pages designed to capture leads, communicate value instantly, and move visitors toward a single measurable action — built with conversion principles, not just visual design.",
    category: "development",
    heroHeadline: "A Landing Page That Converts Visitors Into Leads",
    heroSub: "Built on proven conversion architecture — clear value proposition, smart social proof, and a single call to action your visitors can't ignore.",
    problemHeadline: "Most Landing Pages Look Good and Convert Nothing",
    problems: [
      "Visitors leaving without taking any action",
      "Value proposition unclear or buried below the fold",
      "No lead capture or qualification on the page",
      "Generic design that looks like every other startup",
    ],
    solutionHeadline: "Conversion Architecture First. Design Second.",
    solutionDesc: "We build landing pages starting from the conversion goal and work backwards through copy, structure, social proof, and CTA placement — all designed to move the specific visitor you want to act.",
    outcomes: [
      "Higher conversion rate from day one",
      "Clear and immediate value communication",
      "Lead capture system integrated",
      "A/B test ready structure",
    ],
    whoItFor: [
      "Startups preparing for product launches",
      "Founders running paid traffic campaigns",
      "SaaS products in beta needing waitlist signups",
      "Service businesses replacing generic websites",
    ],
    useCases: [
      { label: "Product launch pages" },
      { label: "Beta and waitlist capture pages" },
      { label: "Paid campaign landing pages" },
      { label: "Lead generation pages" },
      { label: "Event and webinar registration pages" },
    ],
    process: [
      { step: "01", title: "Conversion Strategy", desc: "Define the goal and visitor journey" },
      { step: "02", title: "Copy & Structure", desc: "Write conversion copy and information hierarchy" },
      { step: "03", title: "Design & Build", desc: "High-fidelity design and development" },
      { step: "04", title: "Launch & Track", desc: "Deploy with analytics and tracking" },
    ],
    startingPrice: "₹18,000",
    deliveryTime: "5–10 days",
    formConfig: "startup-landing",
    featured: false,
    iconId: "landing",
    accentColor: "#84CC16",
    gradientFrom: "rgba(132,204,22,0.12)",
  },
  {
    id: "api-integration",
    slug: "api-integration-specialist",
    order: 13,
    title: "API Integration Specialist",
    shortTitle: "API Integration",
    tagline: "Connect anything. Automate everything.",
    description: "Expert API integration services — connecting third-party platforms, building custom integration layers, and ensuring your systems communicate reliably with full error handling and monitoring.",
    category: "development",
    heroHeadline: "Your Tools Should Talk to Each Other Without You Forcing It",
    heroSub: "We build clean, reliable API integrations between any platforms — with proper error handling, monitoring, and documentation so everything stays connected.",
    problemHeadline: "Disconnected Tools Create Operational Friction Every Day",
    problems: [
      "Data that needs to be manually copied between systems",
      "Integrations that break when APIs update",
      "No error handling or monitoring on critical connections",
      "Developer time wasted on repetitive integration work",
    ],
    solutionHeadline: "Reliable Integrations Built With Error Handling and Monitoring",
    solutionDesc: "We build API integrations that don't just work on day one — they stay connected, handle errors gracefully, alert you when something breaks, and have documentation your team can maintain.",
    outcomes: [
      "Reliable data flow between all your platforms",
      "Error handling and automatic retry logic",
      "Monitoring and alerts for critical integrations",
      "Full documentation for every integration",
    ],
    whoItFor: [
      "SaaS products needing third-party integrations",
      "Businesses with disconnected tool stacks",
      "Developers needing specialist integration support",
      "Platforms building a marketplace of integrations",
    ],
    useCases: [
      { label: "Payment gateway integrations" },
      { label: "CRM and marketing tool connections" },
      { label: "ERP and inventory system integrations" },
      { label: "Webhook and event-driven systems" },
      { label: "Custom API development and documentation" },
    ],
    process: [
      { step: "01", title: "Integration Audit", desc: "Map all required connections and data flows" },
      { step: "02", title: "Architecture", desc: "Design integration layer and error handling" },
      { step: "03", title: "Development", desc: "Build, test, and document each integration" },
      { step: "04", title: "Monitor", desc: "Deploy with monitoring and alert systems" },
    ],
    startingPrice: "₹20,000",
    deliveryTime: "1–3 weeks",
    formConfig: "api-integration",
    featured: false,
    iconId: "api",
    accentColor: "#A78BFA",
    gradientFrom: "rgba(167,139,250,0.12)",
  },
  {
    id: "membership-platform",
    slug: "membership-platform-builder",
    order: 14,
    title: "Membership Platform Builder",
    shortTitle: "Membership Platform",
    tagline: "Turn your expertise into recurring monthly revenue.",
    description: "Complete membership platform development — subscription tiers, content gating, member portals, community features, and payment flows — designed to convert one-time buyers into long-term subscribers.",
    category: "development",
    heroHeadline: "Your Knowledge and Content Deserve a Real Membership Platform",
    heroSub: "We build membership systems with tiered access, content gating, and subscription billing — everything you need to build a loyal paying community.",
    problemHeadline: "Makeshift Membership Systems Leak Revenue and Frustrate Members",
    problems: [
      "No proper content gating — members accessing everything free",
      "Manual subscription management wasting hours weekly",
      "Poor member experience causing high churn rates",
      "No analytics on member engagement or retention",
    ],
    solutionHeadline: "A Membership Platform That Grows Your Recurring Revenue",
    solutionDesc: "We build complete membership systems with tiered subscriptions, gated content, member portals, automated billing, and analytics — so you spend time creating, not managing.",
    outcomes: [
      "Automated recurring subscription billing",
      "Tiered content access that drives upgrades",
      "Reduced churn from better member experience",
      "Full analytics on retention and engagement",
    ],
    whoItFor: [
      "Content creators monetizing through memberships",
      "Course creators adding community membership",
      "SaaS products adding member-only features",
      "Businesses building subscription communities",
    ],
    useCases: [
      { label: "Content membership portals" },
      { label: "Community and forum membership systems" },
      { label: "Course and learning membership platforms" },
      { label: "Software subscription access tiers" },
      { label: "Professional membership associations" },
    ],
    process: [
      { step: "01", title: "Access Architecture", desc: "Define tiers, content, and permission model" },
      { step: "02", title: "Billing Setup", desc: "Configure subscription plans and payment flows" },
      { step: "03", title: "Platform Build", desc: "Member portal, content gating, and dashboard" },
      { step: "04", title: "Launch", desc: "Deploy with migration support if needed" },
    ],
    startingPrice: "₹50,000",
    deliveryTime: "4–6 weeks",
    formConfig: "membership-platform",
    featured: false,
    iconId: "membership",
    accentColor: "#14B8A6",
    gradientFrom: "rgba(20,184,166,0.12)",
  },
  {
    id: "custom-crm",
    slug: "custom-crm-build",
    order: 15,
    title: "Custom CRM Build",
    shortTitle: "Custom CRM",
    tagline: "A CRM built around how your team actually sells.",
    description: "Custom CRM systems designed around your specific sales process — not the other way around. Pipeline management, contact intelligence, automation triggers, and reporting built exactly for your business model.",
    category: "development",
    heroHeadline: "Stop Forcing Your Sales Process Into Someone Else's CRM",
    heroSub: "A custom-built CRM that mirrors your exact sales workflow, gives your team what they need, and automates the steps they shouldn't be doing manually.",
    problemHeadline: "Generic CRMs Slow Down the Teams That Should Be Selling",
    problems: [
      "Salespeople spending more time in the CRM than on calls",
      "Pipeline that doesn't match your actual sales stages",
      "No automation for follow-ups and task creation",
      "Paying for features you never use in off-the-shelf tools",
    ],
    solutionHeadline: "A CRM Built for Your Pipeline, Your Team, Your Process",
    solutionDesc: "We map your actual sales process, build a CRM with exactly the fields, stages, and automations you need, and integrate it with your existing tools — no workarounds required.",
    outcomes: [
      "CRM that mirrors your exact sales process",
      "Automated follow-ups and pipeline movement",
      "Higher adoption because it fits how your team works",
      "Full ownership — no monthly SaaS fees",
    ],
    whoItFor: [
      "Sales teams frustrated by generic CRM tools",
      "Businesses with complex or non-standard sales processes",
      "Companies wanting CRM without ongoing SaaS costs",
      "Agencies managing client relationships at scale",
    ],
    useCases: [
      { label: "B2B sales pipeline CRMs" },
      { label: "Agency client relationship management" },
      { label: "Real estate and property CRM systems" },
      { label: "Service business client management" },
      { label: "Internal lead and deal tracking systems" },
    ],
    process: [
      { step: "01", title: "Sales Audit", desc: "Map your complete sales process and stages" },
      { step: "02", title: "CRM Design", desc: "Define fields, views, and automation triggers" },
      { step: "03", title: "Development", desc: "Build the complete CRM with integrations" },
      { step: "04", title: "Onboarding", desc: "Migrate existing data and train your team" },
    ],
    startingPrice: "₹70,000",
    deliveryTime: "5–8 weeks",
    formConfig: "custom-crm",
    featured: false,
    iconId: "crm",
    accentColor: "#EF4444",
    gradientFrom: "rgba(239,68,68,0.12)",
  },
  {
    id: "script-install",
    slug: "script-installation-customization",
    order: 16,
    title: "Script Installation & Customization Service",
    shortTitle: "Script Installation",
    tagline: "Installed correctly. Customized precisely. Working fast.",
    description: "Professional installation and customization of scripts, software, and platforms on your server or hosting — configured to your specifications with troubleshooting, optimization, and documentation included.",
    category: "wordpress",
    heroHeadline: "Get Your Script Running Right the First Time",
    heroSub: "Expert installation, configuration, and customization of any script or platform — deployed on your server and set up exactly the way you need it.",
    problemHeadline: "Bad Installations Cost More Than Good Ones",
    problems: [
      "Scripts installed incorrectly breaking other site functionality",
      "Generic configuration not matching your business requirements",
      "Hours lost to troubleshooting installation errors",
      "No documentation for your team to maintain it later",
    ],
    solutionHeadline: "Installed Once. Configured Right. Documented Fully.",
    solutionDesc: "We handle the complete installation, configuration, and customization of your script — with server optimization, conflict resolution, and full documentation so it runs perfectly long-term.",
    outcomes: [
      "Clean installation with zero conflicts",
      "Configured precisely to your requirements",
      "Server and performance optimized",
      "Full documentation for your team",
    ],
    whoItFor: [
      "Business owners purchasing software scripts",
      "WordPress site owners needing expert setup",
      "Entrepreneurs launching script-based platforms",
      "Agencies needing reliable installation for clients",
    ],
    useCases: [
      { label: "PHP script installation and configuration" },
      { label: "WordPress theme and plugin setup" },
      { label: "Script customization and feature extension" },
      { label: "Server environment configuration" },
      { label: "Troubleshooting broken installations" },
    ],
    process: [
      { step: "01", title: "Requirements", desc: "Define exact configuration and custom needs" },
      { step: "02", title: "Environment Setup", desc: "Prepare server and hosting environment" },
      { step: "03", title: "Install & Configure", desc: "Deploy and configure to your specifications" },
      { step: "04", title: "Test & Document", desc: "Full testing and handover documentation" },
    ],
    startingPrice: "₹5,000",
    deliveryTime: "1–5 days",
    formConfig: "script-install",
    featured: false,
    iconId: "script",
    accentColor: "#64748B",
    gradientFrom: "rgba(100,116,139,0.12)",
  },
  {
    id: "saas-reseller",
    slug: "white-label-saas-reseller-setup",
    order: 17,
    title: "White-Label SaaS Reseller Setup Service",
    shortTitle: "SaaS Reseller Setup",
    tagline: "Build a SaaS reseller business that runs on autopilot.",
    description: "Complete white-label SaaS reseller infrastructure — multi-tenant setup, client sub-accounts, branded billing, reseller dashboard, and automated onboarding so you can sell and scale without manual work.",
    category: "saas",
    heroHeadline: "Build a SaaS Reseller Business Without Building the Software",
    heroSub: "We set up your complete reseller infrastructure — branded platform, automated client onboarding, and a dashboard to manage every account from one place.",
    problemHeadline: "Reselling SaaS Without Infrastructure Means Manual Work at Scale",
    problems: [
      "Manually provisioning every new client account",
      "No branded dashboard to manage all client accounts",
      "Billing and invoicing done manually for every subscription",
      "Clients contacting you for every minor support request",
    ],
    solutionHeadline: "A Reseller Infrastructure That Scales Without Manual Overhead",
    solutionDesc: "We build your complete SaaS reseller system — white-labeled platform, automated client provisioning, branded billing, and a reseller dashboard that gives you full control at any scale.",
    outcomes: [
      "Fully automated client onboarding",
      "Branded dashboard for complete client management",
      "Automated subscription billing and invoicing",
      "Scalable to hundreds of clients without extra overhead",
    ],
    whoItFor: [
      "Agencies building a SaaS reseller revenue stream",
      "Entrepreneurs entering the SaaS reseller market",
      "Businesses already reselling and needing better infrastructure",
      "Freelancers productizing services into managed SaaS",
    ],
    useCases: [
      { label: "Multi-client SaaS reseller dashboards" },
      { label: "Automated client account provisioning" },
      { label: "Branded billing and subscription management" },
      { label: "White-label support portal for clients" },
      { label: "Reseller analytics and revenue tracking" },
    ],
    process: [
      { step: "01", title: "Reseller Model", desc: "Define pricing, tiers, and client management needs" },
      { step: "02", title: "Platform Setup", desc: "Configure multi-tenant system and branding" },
      { step: "03", title: "Automation Build", desc: "Onboarding, billing, and provisioning automation" },
      { step: "04", title: "Launch", desc: "Go live with your first client acquisitions" },
    ],
    startingPrice: "₹55,000",
    deliveryTime: "2–4 weeks",
    formConfig: "saas-reseller",
    featured: true,
    iconId: "reseller",
    accentColor: "#D946EF",
    gradientFrom: "rgba(217,70,239,0.12)",
  },
  {
    id: "saas-development",
    slug: "saas-development",
    order: 18,
    title: "Custom SaaS Development",
    shortTitle: "SaaS Development",
    tagline: "Fully architected SaaS platforms built to handle real traffic and generate recurring revenue.",
    description: "We architect and build complete Software-as-a-Service platforms from scratch. Whether you're an enterprise modernizing internal workflows or a founder launching a new subscription product, we build SaaS that actually scales.",
    category: "saas",
    heroHeadline: "Stop Building Prototypes. It's Time to Build a Business.",
    heroSub: "We architect and build complete, production-ready SaaS platforms with integrated subscription billing, robust authentication, and scalable infrastructure. Handed over ready for launch.",
    problemHeadline: "Building SaaS Correctly Requires More Than Just Frontend Code",
    problems: [
      "Without the right architecture, products fail under load or become technical debt.",
      "Generic boilerplates can't handle complex business logic.",
      "Subscription billing logic is notoriously difficult to get right.",
      "Security and data segregation are often an afterthought.",
    ],
    solutionHeadline: "Full-Stack Platforms Built on Enterprise-Grade Infrastructure",
    solutionDesc: "We build full-stack web applications prioritizing clean architecture, responsive UX/UI, Stripe billing integration, and enterprise-grade security. Ready for scale from day one.",
    outcomes: [
      "Production-ready scalable architecture",
      "Integrated subscription billing and payments",
      "Secure, role-based access control",
      "Fast, responsive, premium UI/UX",
    ],
    whoItFor: [
      "Founders launching new SaaS products",
      "Enterprises digitizing complex internal workflows",
      "Startups scaling beyond their initial MVP",
      "Businesses moving from on-premise to cloud SaaS",
    ],
    useCases: [
      { label: "B2B Subscription Platforms" },
      { label: "Internal Workflow Dashboards" },
      { label: "Web3 & AI-Powered SaaS Tools" },
      { label: "Data Analytics & Reporting Portals" },
      { label: "Client & Vendor Management Systems" },
    ],
    process: [
      { step: "01", title: "Architecture Design", desc: "System design, database schema, and technical blueprint." },
      { step: "02", title: "Core Infrastructure", desc: "Auth, database clustering, and Stripe integration." },
      { step: "03", title: "Feature Build", desc: "Frontend UI/UX and core business logic implementation." },
      { step: "04", title: "Testing & Launch", desc: "Performance testing and zero-downtime deployment." },
    ],
    startingPrice: "₹1,50,000",
    deliveryTime: "8-12 weeks",
    formConfig: "saas-development",
    featured: true,
    iconId: "saas",
    accentColor: "#F43F5E",
    gradientFrom: "rgba(244,63,94,0.12)",
  },
  {
    id: "ai-automation",
    slug: "ai-automation",
    order: 19,
    title: "End-to-End AI Automation",
    shortTitle: "AI Automation",
    tagline: "Replace slow human bottlenecks with intelligent, 24/7 AI systems.",
    description: "We build fully autonomous AI workflows, multi-agent systems, and custom LLM integrations that don't just 'assist' your team—they completely take over high-volume, repetitive business processes.",
    category: "ai",
    heroHeadline: "Your Competitors Are Automating. You Are Still Paying for Manual Labor.",
    heroSub: "Stop running operations on spreadsheets and manual routing. We integrate custom AI agents that ingest data, make autonomous decisions, and execute tasks across your entire software stack without taking a single break.",
    problemHeadline: "Human Error and Processing Limits Are Capping Your Growth",
    problems: [
      "High operational costs from employing humans for repetitive tasks.",
      "Slow response and processing times due to natural human bottlenecks.",
      "Inconsistent outputs and costly manual errors when handling high-volume data.",
      "Your most talented people are stuck doing data-entry instead of strategic work.",
    ],
    solutionHeadline: "Multi-Agent AI Systems Custom-Trained for Your Operations",
    solutionDesc: "We don't just install off-the-shelf wrappers. We architect custom RAG pipelines, API-integrated LLM orchestrators, and autonomous agent swarms that perfectly replicate your standard operating procedures.",
    outcomes: [
      "60-80% reduction in manual operational costs",
      "24/7 autonomous task execution and data processing",
      "Zero human error in automated workflows",
      "Employees freed to focus exclusively on revenue-generating strategy",
    ],
    whoItFor: [
      "Enterprises drowning in manual data entry or routing",
      "Agencies wanting to scale output without hiring more staff",
      "Customer support teams overwhelmed by high ticket volume",
      "Operations managers looking to optimize unit economics",
    ],
    useCases: [
      { label: "Multi-Agent Customer Support Triage" },
      { label: "Autonomous Invoice & Document Processing" },
      { label: "Dynamic Data Enrichment & CRM Entry" },
      { label: "RAG-Powered Internal Knowledge Bases" },
      { label: "Automated Lead Qualification & Booking" },
    ],
    process: [
      { step: "01", title: "Workflow Audit", desc: "Map your manual SOPs and identify the highest-ROI automation targets." },
      { step: "02", title: "AI Architecture", desc: "Design multi-agent logic, RAG pipelines, and necessary API integrations." },
      { step: "03", title: "Development", desc: "Train custom LLM agents and connect them to your software stack." },
      { step: "04", title: "Deployment", desc: "Launch shadows to test outputs, then hand over full autonomy." },
    ],
    startingPrice: "₹1,20,000",
    deliveryTime: "4-8 weeks",
    formConfig: "ai-automation",
    featured: true,
    iconId: "ai",
    accentColor: "#6366F1",
    gradientFrom: "rgba(99,102,241,0.12)",
  },
  {
    id: "tech-consulting",
    slug: "tech-consulting",
    order: 20,
    title: "Technical Architecture & CTO Consulting",
    shortTitle: "Tech Consulting",
    tagline: "Stop guessing with your tech stack. Build an architecture that scales.",
    description: "We provide fractional CTO advisory and technical architecture consulting for fast-growing startups and enterprises. We align your software roadmap with your business goals so you build it right the first time.",
    category: "consulting",
    heroHeadline: "Bad Technical Decisions Cost Six Months and Six Figures. Let's Prevent That.",
    heroSub: "We audit your current systems, define scalable cloud architecture, and create strict engineering roadmaps. You get the strategic execution of a seasoned CTO without the full-time equity cost.",
    problemHeadline: "Unscalable Architecture Kills Startups",
    problems: [
      "Non-technical founders hiring the wrong agency and getting a bloated MVP.",
      "Building on the wrong tech stack, leading to massive technical debt.",
      "Products crashing under user load due to poor database design.",
      "Paying a $150k/year full-time CTO before reaching product-market fit.",
    ],
    solutionHeadline: "Bulletproof Architecture Planned Before a Single Line of Code",
    solutionDesc: "We don't guess. We map out your entire database schema, API integrations, and cloud infrastructure requirements to ensure the product you build today will survive scale tomorrow.",
    outcomes: [
      "Scalable, future-proofed application architecture",
      "Cost-optimized AWS/Vercel cloud infrastructure",
      "Clear, actionable engineering roadmaps",
      "Fractional executive leadership without the equity dilution",
    ],
    whoItFor: [
      "Non-technical founders launching complex software products",
      "Startups hitting critical scaling bottlenecks",
      "Companies dealing with legacy code and massive technical debt",
      "Enterprises looking to modernize internal systems",
    ],
    useCases: [
      { label: "Current Codebase & Infrastructure Audits" },
      { label: "Fractional CTO & Developer Management" },
      { label: "Cloud Migration & Cost Optimization" },
      { label: "Project Rescue for Dropped Builds" },
      { label: "Database Scaling & Performance Tuning" },
    ],
    process: [
      { step: "01", title: "Technical Audit", desc: "Review your current codebase, architecture, and cloud costs." },
      { step: "02", title: "Strategic Roadmap", desc: "Design the scalable architecture blueprint and sprint plan." },
      { step: "03", title: "Execution Advisory", desc: "Guide your developers through complex implementation hurdles." },
      { step: "04", title: "Ongoing Support", desc: "Act as your fractional CTO for critical technical decisions." },
    ],
    startingPrice: "₹75,000 / mo",
    deliveryTime: "Ongoing",
    formConfig: "tech-consulting",
    featured: true,
    iconId: "consulting",
    accentColor: "#10B981",
    gradientFrom: "rgba(16,185,129,0.12)",
  },
  {
    id: "website-systems",
    slug: "website-systems",
    order: 21,
    title: "High-Performance Website Systems",
    shortTitle: "Website Systems",
    tagline: "Stop losing customers to slow, generic templates. Get a custom-engineered web presence.",
    description: "We build modern, statically generated web applications using React and Next.js. You get sub-second load times, unbreakable security, aggressive technical SEO, and an integrated headless CMS.",
    category: "development",
    heroHeadline: "Your Website is Costing You Sales Every Second It Takes to Load.",
    heroSub: "We don't just 'design websites.' We engineer lightning-fast, conversion-optimized Next.js web systems that dominate search rankings and turn clicks into revenue.",
    problemHeadline: "Bloated Templates Are Killing Your Marketing ROI",
    problems: [
      "3+ second load times causing 53% of mobile traffic to abandon the site.",
      "Constant security vulnerabilities and plugin updates in WordPress.",
      "Poor Core Web Vitals scores permanently destroying your SEO rankings.",
      "Generic templates that make your brand look exactly like your competitors.",
    ],
    solutionHeadline: "Custom-Engineered Platforms Built for Speed and Scale",
    solutionDesc: "We ditch the bloated page builders. We code your site from the ground up using enterprise-grade frameworks (Next.js/React), delivering instant page loads and beautiful, interactive UI.",
    outcomes: [
      "Sub-second page load times across all devices",
      "Perfect 100/100 Google Lighthouse & Core Web Vitals scores",
      "Unbreakable security with static generation",
      "Headless CMS integration for effortless content management",
    ],
    whoItFor: [
      "Companies spending aggressively on ads who need higher conversion rates",
      "Brands wanting premium, interactive, Apple-like web experiences",
      "Businesses frustrated by slow, hacked WordPress sites",
      "Agencies looking for flawless technical execution for their clients",
    ],
    useCases: [
      { label: "Premium Corporate Brand Websites" },
      { label: "High-Traffic Content Portals & Blogs" },
      { label: "Interactive WebGL & Framer Motion Experiences" },
      { label: "Headless eCommerce Frontends" },
      { label: "SEO-Optimized Programmatic Landing Pages" },
    ],
    process: [
      { step: "01", title: "UX/UI Design", desc: "Figma wireframing and high-fidelity interactive prototyping." },
      { step: "02", title: "Frontend Build", desc: "Pixel-perfect Next.js development with Framer Motion animations." },
      { step: "03", title: "CMS Integration", desc: "Wiring up a headless CMS (Sanity/Strapi) for easy editing." },
      { step: "04", title: "Optimization", desc: "Technical SEO, caching, and Core Web Vitals optimization before launch." },
    ],
    startingPrice: "₹60,000",
    deliveryTime: "3-6 weeks",
    formConfig: "website-systems",
    featured: true,
    iconId: "globe",
    accentColor: "#3B82F6",
    gradientFrom: "rgba(59,130,246,0.12)",
  },
];

export const getFeaturedServices = () =>
  services.filter((s) => s.featured);

export const getServiceBySlug = (slug: string) =>
  services.find((s) => s.slug === slug);

export const getServicesByCategory = (cat: ServiceCategory) =>
  services.filter((s) => s.category === cat);

const initialCategories: { id: ServiceCategory; label: string; count: number }[] = [
  { id: "ai", label: "AI & Automation", count: 0 },
  { id: "saas", label: "SaaS", count: 0 },
  { id: "development", label: "Development", count: 0 },
  { id: "wordpress", label: "WordPress", count: 0 },
  { id: "automation", label: "Automation", count: 0 },
  { id: "consulting", label: "Consulting", count: 0 },
  { id: "maintenance", label: "Maintenance", count: 0 },
];

export const serviceCategories = initialCategories.map((cat) => ({
  ...cat,
  count: services.filter((s) => s.category === cat.id).length,
}));
